
/* NOTE: This file is auto-generated from authors.xml, do not edit it. */

static const gchar * const creators[] =
{
  "Spencer Kimball",
  "Peter Mattis",
  NULL
};

static const gchar * const maintainers[] =
{
  "Sven Neumann",
  "Michael Natterer",
  NULL
};

static const gchar * const authors[] =
{
  "Spencer Kimball",
  "Peter Mattis",
  "Sven Neumann",
  "Michael Natterer",
  "Fredrik Alströmer",
  "Rob Antonishen",
  "Jerry Baker",
  "Hendrik Boom",
  "Richard Bowers",
  "Hans Breuer",
  "Ingo Brückl",
  "Simon Budig",
  "João S. O. Bueno",
  "Seth Burgess",
  "Marco Ciampa",
  "Winston Chang",
  "Lars-Peter Clausen",
  "Sven Claussner",
  "Kevin Cozens",
  "Alexia Death",
  "Nicholas Doyle",
  "Daniel Eddeland",
  "Ulf-D. Ehlert",
  "Saul Goode",
  "David Gowers",
  "Cameron Gregory",
  "Eric Grivel",
  "Stephen Griffiths",
  "Tim Harder",
  "Michael Henning",
  "Lukasz Hladowski",
  "Patrick Horgan",
  "Daniel Hornung",
  "Christopher Howard",
  "Alexander Hämmerle",
  "Barak Itkin",
  "Javier Jardón",
  "Tim Jedlicka",
  "Jehan",
  "Róman Joost",
  "Alexander Jones",
  "Aurimas Juška",
  "Malay Keshav",
  "Øyvind Kolås",
  "Lloyd Konneker",
  "Kretynofil",
  "Christian Krippendorf",
  "Eric Lamarque",
  "Simone Karin Lehmann",
  "Dave Lichterman",
  "Tor Lillqvist",
  "Mikael Magnusson",
  "Luidnel Maignan",
  "Thomas Manni",
  "Takeshi Matsuyama",
  "Téo Mazars",
  "Mike Melancon",
  "Christopher Montgomery",
  "Tobias Mueller",
  "Michael Muré",
  "Andreas Neustifter",
  "Jon Nordby",
  "Martin Nordholts",
  "David Odin",
  "Nelson A. de Oliveira",
  "Victor Oliveira",
  "Benjamin Otte",
  "Petr Ovtchenkov",
  "Ville Pätsi",
  "Akkana Peck",
  "Nils Philippsen",
  "Mircea Purdea",
  "Dennis Ranke",
  "Martin Renold",
  "Kristian Rietveld",
  "Gilles Rochefort",
  "Marco Rossini",
  "Karthikeyan S",
  "Daniel Sabo",
  "Enrico Schröder",
  "Michael Schumacher",
  "Peter Sikking",
  "RyōTa SimaMoto",
  "SHIRAKAWA Akira",
  "Jernej Simončič",
  "Manish Singh",
  "Mukund Sivaraman",
  "Ville Sokk",
  "Jakub Steiner",
  "Omari Stephens",
  "Bogdan Szczurek",
  "Tal Trachtman",
  "Mason Thomas",
  "Andreas Turtschan",
  "Massimo Valentini",
  "Thorsten Vollmer",
  "Clayton Walker",
  "Rupert Weber",
  "Alexis Wilhelm",
  "Andrew Wyatt",
  "Yoshinori Yamakawa",
  "Zhenfeng Zhao",
  "Simon Zilliken",
  "Przemyslaw Zych",
  NULL
};

static const gchar * const artists[] =
{
  "Alexia Death",
  "Ville Pätsi",
  "Jakub Steiner",
  "Bernhard Stockmann",
  NULL
};

static const gchar * const documenters[] =
{
  "Marco Ciampa",
  "Sven Claussner",
  "Ulf-D. Ehlert",
  "Róman Joost",
  "Alexandre Prokoudine",
  NULL
};
